name: CI

on: [push]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      # setup
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.15.8'
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      # prepare
      - run: cd web; npm ci
      - run: GO111MODULE=off go get github.com/rakyll/statik
      - run: cd web; ./node_modules/.bin/vue-cli-service build
      - run: statik -src=./web/dist -dest=./pkg/server

      # build
      - run: CGO_ENABLED=0 go build -a -o ./terjang ./cmd/terjang/

      # test
      - run: go test -v ./test/...

