name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-20.04
    permissions:
      packages: write
    steps:
      # setup
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.16.4'
      - uses: actions/setup-node@v2
        with:
          node-version: '14'

      # prepare
      - run: npm install -g npm
      - run: cd web; npm ci
      - run: cd web; ./node_modules/.bin/vue-cli-service build

      # build
      - run: CGO_ENABLED=0 go build -a -o ./terjang ./cmd/terjang/

      # test
      - run: go test -v ./test/...

      # goreleaser and build docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: andylibrian
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Install GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          install-only: true
      - name: GoReleaser
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [[ $GITHUB_REF == refs/heads/main ]]; then
            goreleaser --snapshot
          fi
      - name: docker push
        run: |
          if [[ $GITHUB_REF == refs/heads/main ]]; then
            docker push ghcr.io/andylibrian/terjang:latest
            docker push ghcr.io/andylibrian/terjang:dev-amd64
          fi
